### ISSUE TITLE
Plugin install can't resolve module 

### ISSUE THREAD

**Issue by Kikketer** [elastic/kibana-plugin-helpers#18] opened 2016-11-17 21:39 UTC
So I have a symlink (or just a full copy) of a plugin that I'm working on inside the `/plugins` folder.  For this example let's say it's https://github.com/Kikketer/generic-feedback-plugin.

Simply clone that plugin and place it along side `/kibana` (same parent).  Then create a symlink in the `/kibana/plugins` directory called "generic-feedback-plugin" that points to the "generic-feedback-plugin" folder (the one you just cloned).

All is well, right up until you decide to install another plugin:
```
./bin/kibana-plugin install x-pack
```

After a bit I get this error:
```
    ERROR in ./optimize/bundles/status_page.entry.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/***/Documents/htdocs/kibana/plugins/generic-feedback-plugin/public/public/feedback in /Users/***/Documents/htdocs/kibana/optimize/bundles
     @ ./optimize/bundles/status_page.entry.js 35:0-58
```
(the *** mask my ID, still figuring out the compliance stuff)

Note the `/public/public` part in the folder.  That seemed odd to me, so I removed `/public` from the hack in the index.js.  But it then just said the same error with no `/public` folder in it at all.  Smells like it's doing something odd there.

**Comment by spalger** [comment] 2016-11-18 16:35
Yeah, the `/public` issue is almost certainly caused by the module id `'plugins/feedback-plugin/public/feedback'`

If you change it to `'plugins/feedback-plugin/feedback'`, and there is a `feedback.js` file in that directory, then everything should work.

If there isn't a `feedback.js` file in the root of your plugin folder and the stars are aligned in a specific way, you might encounter a bug that requires you to specify one more path segment, like `'plugins/feedback-plugin/public/feedback/index.js'` or something

**Comment by Kikketer** [comment] 2016-11-18 18:43
The trick is the `feedback.js` file is in the `/public` folder.  What you are saying is that I should move that to the root?

Here are my tests:
**Test-1**: Have `plugins/generic-feedback-plugin/public/feedback` set in `index.js` and have that file actually exist.
Do a build of this generic plugin, and install it via `./bin/kibana-plugin install file:///...`

It throws the error I originally reported above:

```
 ERROR in ./optimize/bundles/status_page.entry.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/***/Documents/htdocs/kibana/plugins/generic-feedback-plugin/public/public/feedback in /Users/***/Documents/htdocs/kibana/optimize/bundles
     @ ./optimize/bundles/status_page.entry.js 35:0-58
```

**Test-2**: Remove `/public` to have the string: `plugins/generic-feedback-plugin/feedback` but not have a `feedback.js` file in the root of the plugin.
Do a build of this generic plugin, and install it via `./bin/kibana-plugin install file:///...`

This actually worked!  But isn't 100% of the original problem because I did a build, I would rather symlink to all the plugins so I can actively develop them and have just kibana running (which then rebuilds and optimizes if any of the plugins change).

**Test-3**: Add a simple `feedback.js` file to the root of the plugin that has nothing else but:

```
import './public/feedback';
```

This worked as well, however since not having the extra `feedback.js` file there also worked, I'm pretty sure it's doing nothing.

**Test-4**: Do this all the symlink style.  Have the generic plugin symlinked into the `/plugins` directory and attempt to install x-pack.
`plugins/generic-feedback-plugin/feedback`
Just have it symlinked and attempt to install x-pack `./bin/kibana-plugin install x-pack`

This also worked.  So as I was writing this I expected to get an error here (as it's exactly the same as the original issue).  Not sure what's going on here but it seems things are happy enough for now.

I've pushed a workaround branch to the generic-feedback-plugin.  https://github.com/Kikketer/generic-feedback-plugin/tree/workaround

**Comment by Kikketer** [comment] 2016-11-18 19:59
Ok we can close this now, I've not run into the issue as long as I don't do anything until the init.  I had compared the generic version of feedback to my real version and the only remaining difference was the use of the crypto stuff in the config (again).  I moved that to only occur during the init and all seems to build well together now.

**Comment by spalger** [comment] 2016-11-18 23:35
> What you are saying is that I should move that to the root?

Sorry, I wasn't clear.

Within the [uiExports](https://github.com/Kikketer/generic-feedback-plugin/blob/workaround/index.js#L3-L11) block of your plugin definition, all the the module id's that start with `plugins/generic-feedback-plugin/...` will point to your plugin's public directory. That means that the module id `plugins/generic-feedback-plugin/feedback` will resolve to the `{{project}}/plugins/generic-feedback-plugin/public/feedback.js` file.

The way the module ids resolve in Kibana is actually kind of crazy, but here is a full breakdown of how it works: https://github.com/elastic/kibana/wiki/Resolving-Require-Paths. The rule I'm describing is `2.ii`.

---

Glad to hear you got it working. If you want to do some quicker chat you can ping me in #kibana on freenode

**Closed as completed by spalger** 2016-11-18 23:35 UTC
